### ISSUE TITLE
[QUESTION] 

### ISSUE THREAD

**Issue by HelixHEX** [mrousavy/react-native-blurhash#110] opened 2021-02-10 14:53 UTC
# Question
I keep getting a weird error when I render the component

# Environment

```
"BlurhashView" was not found in the UIManager."
```

```json
"react": 16.13.1,
"react-native": ~0.63.4,
"react-native-blurhash": ^1.0.30"
```

**Comment by anton25360** [comment] 2021-02-10 16:57
I'm getting this error too, would be good to have a fix

**Comment by mrousavy** [comment] 2021-02-10 17:49
1. Do you get the error on Android and iOS?
2. Did you run `pod install`?

**Comment by anton25360** [comment] 2021-02-11 08:45
> 1. Do you get the error on Android and iOS?
> 2. Did you run `pod install`?
> 3. Does it work on version 1.0.29?

1. yes to both
2. yes
3. getting the same error on 1.0.29

**Comment by mrousavy** [comment] 2021-02-11 10:25
Since I cannot reproduce, please try cleaning everything and rebuilding it:

1. Open Xcode and press **Product** > **Clean Build Folder**

2. Run these commands:
    ```
    rm -rf node_modules && rm -rf package-lock.json
    rm -rf ios/Pods/ && rm -rf ios/Podfile.lock
    npm i
    cd ios
    pod repo update && pod install
    ```

If the error still occurs, could you provide a minimal reproduceable sample repository which I can clone and see for myself?

**Comment by mrousavy** [comment] 2021-02-11 10:26
Oh a few more things I thought of:

1. Are you using the experimental renderer "Fabric"?
2. Could you show me your complete package.json file?
3. Did you autolink react native blurhash with the `react-native link react-native-blurhash` command? If so, please unlink as it is autolinked

**Comment by anton25360** [comment] 2021-02-12 12:13
Cleaning the project and reinstalling pods worked! (Had new pod errors pop up, that might have had something to with it not working)
Thanks!

**Comment by mrousavy** [comment] 2021-02-12 12:15
@anton25360 awesome, I'll close this issue then. @HelixHEX if the above steps still didn't fix the issue for you feel free to comment and I'll re-open

**Closed by mrousavy** 2021-02-12 12:15 UTC
Labels: question
